FROM node:16.2.0-alpine

RUN apk update && apk upgrade

WORKDIR /app

COPY package.json .

RUN yarn install

COPY . .

EXPOSE 3000

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000


RUN yarn build


CMD [ "yarn", "start" ] 